# Generated by Django 4.2.16 on 2024-11-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
