# Generated by Django 4.2.16 on 2024-11-15 15:56

import date.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0003_alter_date_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetAll',
        ),
        migrations.AddField(
            model_name='date',
            name='created_at',
            field=models.DateTimeField(default=date.models.get_created_at_default),
        ),
        migrations.AddField(
            model_name='date',
            name='deleted_at',
            field=models.DateTimeField(default=date.models.get_deleted_at_default),
        ),
        migrations.AddField(
            model_name='date',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
