# Generated by Django 4.2.16 on 2024-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0004_delete_getall_date_created_at_date_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='status',
            field=models.CharField(default='未完成', max_length=20),
        ),
    ]
